<?php
///**
// * @var $block View
// */
//
//use Codilar\EmployeeDetails\Block\Adminhtml\Order\View\View;
//
//?>
<!--<div class="admin__page-section-item order-custom-information">-->
<!--    <div class="admin__page-section-item-title">-->
<!--        <span class="title">Custom Information</span>-->
<!--    </div>-->
<!--    <div class="admin__page-section-item-content">-->
<!--        <div class="order-custom-information-title">Add custom block information</div>-->
<!--    </div>-->
<!--</div>-->
<h3>Check the print value..</h3>
